<Screen2>:
    name: 'screen2'
    image1:image1
    Image:

        id:image1

        source:''
        allow_stretch :True
        keep_ratio:False
    MDRaisedButton:
        text: "Back"
        pos_hint: {'center_x': 0.1}
        size_hint_x:None
        on_release: root.go_back()

    MDToolbar:
        title:"Type To Write"
        pos_hint:{'top':1}
        size_hint_y :0.05
        left_action_items: [["menu",lambda x:root.parent.parent.back()]]
