<TypeToWriteScreen>:
    #:import utils kivy.utils
    background: "typetowritescreen/background.jpg"
    canvas.before:
        Color:
            rgba:utils.get_color_from_hex("#ebeacc")
        Rectangle:
            size: self.size
            pos: self.pos
            source:root.background

    ScreenManager:
        id: screen_manager
        Screen1:
            id:screen1
            name: "screen1"
        Screen2:
            id:screen2
            name: "screen2"





